resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: aem_test
      path: Tech314/ReimbursementProject
      branches:
        include: master        
  - name: test
    type: BuildInfo
    configuration:
      sourceArtifactory: default-maven-artifactory
pipelines:  
  - name: build
    steps:
      - name: step_1
        type: MvnBuild
        configuration:
          inputResources:
            - name: myGitRepo  
          mvnCommand: clean install
          forceXrayScan: true
          failOnScan: false
          integrations:
            - name: test
        execution:
          onExecute:
            - echo "Building..."
