resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: aem_test
      path: Tech314/ReimbursementProject
      branches:
        include: master
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: default-maven-virtual
      buildName: Test
      buildNumber: 1          
pipelines:  
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo            
        execution:
          onExecute:
            - mvn clean install
